---
# https://pages.github.com/versions/
fork: true
repo_slug: vszakats/hb
site_slug: vszakats/hb
repo_branch: main
site_branch: main
site_root: docs/
dl_url: https://github.com/vszakats/hb/releases
short_version: "3.4"
full_version: "3.4.0dev"
license_file: LICENSE.txt
ilink_suffix: ""

exclude: ['*.pem', '*.sh']

example_categories:
  - basic
  - arrays
  - database
  - extensions
  - web
collections:
  example:
    output: true
defaults:
  - scope:
      path: ""
      type: example
    values:
      layout: example

incremental: true
sass:
  style: compressed
